Hometask from lecture 36. Flask and databases
bogdanbasii/test-repo pull request #21
Opened 2023-04-05 11:01 UTC by bogdanbasii

Important data hidden in .env file. Classes created in models.py. Endpoints were modified and created in views.py

2023-04-14 17:42 UTC, klymenok requested changes

2023-04-14 17:42 UTC, klymenok commented on FlaskProject/.env
> +SECRET_KEY=some-test-secret
.env файл не потрібно пушити на репозиторій

2023-04-14 17:42 UTC, klymenok commented on FlaskProject/robot_app/__init__.py
> +app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///robot-database.sqlite'
Ви можете взяти значення із env, а не хардкодити його

2023-04-15 08:56 UTC, bogdanbasii commented on FlaskProject/robot_app/__init__.py
> +app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///robot-database.sqlite'
Зміни внесено

2023-04-15 08:56 UTC, bogdanbasii commented on FlaskProject/.env
> +SECRET_KEY=some-test-secret
Файл видалено

2023-04-17 20:14 UTC, klymenok approved these changes
Looks good!

2023-04-19 16:47 UTC, merged